"""create learning_content table

Revision ID: 13a12de84cbb
Revises: 17883d42373c
Create Date: 2024-03-24 17:48:26.071515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13a12de84cbb'
down_revision: Union[str, None] = '17883d42373c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_content',
    sa.Column('learning_content_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('content_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('learning_content_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_content')
    # ### end Alembic commands ###
